require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
